languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "«Алгебры Ли, алгебраические группы и теория инвариантов»"
baseURL = "https://lie-school.ru/"

# sectionPagesMenu = "main"    


[blackfriday]
  angledQuotes = true
  fractions = false
  
[markup.goldmark.renderer] 
  unsafe= true 
  
[menu]
[[menu.menu_2023]]
  name = 'О школе'
  url = '/2023'
  weight = -80
[[menu.menu_2023]]
  name = 'Расписание'
  url = '/2023/schedule.pdf'
  weight = -60
[[menu.menu_2023]]
  name = 'Лекционные курсы'
  url = '/2023/lectures'
  weight = -50
[[menu.menu_2023]]
  name = 'Сборник тезисов и материалы курсов'
  url = '/2023/papers'
  weight = -40
[[menu.menu_2023]]
  name = 'Программный и организационный комитеты'
  url = '/2023/orgs'
  weight = -30
[[menu.menu_2023]]
  name = 'Зарегистрированные участники'
  url = '/2023/list'
  weight = -20
[[menu.menu_2023]]
  name = 'Расположение'
  url = '/2023/contacts'
  weight = -10
[[menu.menu_2023]]
  name = 'Фотографии'
  url = '/2023/photo'
  weight = -5
[[menu.menu_2023]]
  name = 'На главную'
  url = '/'
  weight = 0

[[menu.menu_2024]]
  name = 'О школе'
  url = '/2024'
  weight = -80
[[menu.menu_2024]]
  name = 'Расписание'
  url = '/2024/shedule.pdf'
  weight = -60
[[menu.menu_2024]]
  name = 'Лекционные курсы'
  url = '/2024/lectures'
  weight = -50
[[menu.menu_2024]]
  name = 'Программный и организационный комитеты'
  url = '/2024/orgs'
  weight = -30
[[menu.menu_2024]]
  name = 'Зарегистрированные участники'
  url = '/2024/list'
  weight = -20
[[menu.menu_2024]]
  name = 'На главную'
  url = '/'
  weight = 0

